/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sp2;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import javax.swing.text.JTextComponent;

/**
 *
 * @author julien.leleu
 */
public class Interface extends javax.swing.JDialog {
    
    ResultSet re;
    String[] resuTab;
    
    
    
    
    
    
    
    
    /**
     * Creates new form Interface
     */
    public Interface(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        charge = new javax.swing.JButton();
        quit = new javax.swing.JButton();
        verif = new javax.swing.JLabel();
        listProd = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Application.");

        jLabel1.setText("Code du client :");

        charge.setText("Charger les données");
        charge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chargeMouseClicked(evt);
            }
        });

        quit.setText("Quitter");
        quit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitMouseClicked(evt);
            }
        });

        listProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Charger les producteurs");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(listProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                                .addComponent(charge))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(quit)))
                .addGap(18, 18, 18)
                .addComponent(verif, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(verif, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(charge)
                            .addComponent(listProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(103, 103, 103)
                        .addComponent(quit)
                        .addGap(38, 38, 38))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitMouseClicked
        //quitter l'application
        System.exit(0);
    }//GEN-LAST:event_quitMouseClicked

    private void chargeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chargeMouseClicked
        String cde;
        
        cde=listProd.getSelectedItem().toString();
        
        String str[] = cde.split(" / ");
        cde=str[0];
        if(cde != ""){
                        
            try{
                //on crée une connexion
                Connection con;

                //la voila on charge le driver
                Class.forName("org.gjt.mm.mysql.Driver");
                
                //on charge la connexion
                con = DriverManager.getConnection("jdbc:mysql://localhost/etudecas","root","root");
                
                //on cree ce qu'on doit faire sur l'objet que l'on doit faire.... tres philosophique je sais
                Statement statement = con.createStatement();
                
                //on execute une requete SELECT
                re = statement.executeQuery( "SELECT com.IdCommande, cli.IdClient, cli.NomClient, pro.NomSociete, pro.IdProducteur, ver.NomVerger, con.Quantite,typ.Libelle, typ.Poids FROM client cli, commande com, lot , livraison liv, verger ver, producteur pro, conditionner con, typeconditionnement typ \n" +
"WHERE cli.IdClient=com.IdClient\n" +
"AND con.IdCommande=com.IdCommande\n" +
"AND typ.IdConditionnement=con.IdConditionnement\n" +
"AND com.IdLot=lot.IdLot\n" +
"AND lot.IdLivraison=liv.IdLivraison\n" +
"AND liv.IdVerger=ver.IdVerger\n" +
"AND ver.IdProducteur=pro.IdProducteur\n" +
"AND pro.IdProducteur='"+ cde +"'"+
"ORDER BY com.IdCommande"       );     
                
                //comme ca on stocke le resultat NON ouvert
               
                //on compte le nombre de ligne 
                if(!re.first()){
                    verif.setText("<html><b>Statut :</b><br> Client non trouvé <br> OU <br> aucune commande en cours</html>");
                    
                }
                else{
                    verif.setText("<html><b>Statut :</b><br> Données chargées</html>");
                    
                    String numCommande="";
                    int prems=0;
                    
                    Fichier XML = new Fichier();
                    XML.ouvrir("J:/FichierXMLJavaAgrur2.xml", "W");
                    XML.ecrire("<?xml version=\"1.0\"?>\n");
                    do{
                        //si je suis sur la meme commande j'ecris que le conditionnement
                        if(numCommande.equals(re.getString(1))){
                            XML.ecrire("<detail>\n");
                            XML.ecrire("    <Quantite>"+re.getString(7)+"</Quantite>\n");
                            XML.ecrire("    <Libelle>"+re.getString(8)+"</Libelle>\n");
                            XML.ecrire("    <Poids>"+re.getString(9)+"</Poids>\n");
                            XML.ecrire("</detail>\n");
                            
                        }
                        //sinon j'ecrit une nouvelle commande et le detail du premier conditionnement
                        else{
                            
                            numCommande=re.getString(1);
                            if(prems==1){
                                XML.ecrire("</commande>\n");
                                
                            }
                            prems=1;
                            //nouvelle commande donc on detail la provenance
                            XML.ecrire("<commande>\n");
                            XML.ecrire("<IdCommande>"+re.getString(1)+"</IdCommande>\n");
                            XML.ecrire("<IdClient>"+re.getString(2)+"</IdClient>\n");
                            XML.ecrire("<NomClient>"+re.getString(3)+"</NomClient>\n");
                            XML.ecrire("<IdProd>"+re.getString(5)+"</IdProd>\n");
                            XML.ecrire("<SocieteProd>"+re.getString(4)+"</SocieteProd>\n");
                            XML.ecrire("<NomVerger>"+re.getString(6)+"</NomVerger>\n");
                            //detail de la commande
                            XML.ecrire("<detail>\n");
                            XML.ecrire("    <Quantite>"+re.getString(7)+"</Quantite>\n");
                            XML.ecrire("    <Libelle>"+re.getString(8)+"</Libelle>\n");
                            XML.ecrire("    <Poids>"+re.getString(9)+"</Poids>\n");
                            XML.ecrire("</detail>\n");
                            
                        }
                         
                    }while(re.next());
                    XML.ecrire("</commande>\n");
                    XML.fermer();
                    
                    
                }
            }
            catch(Exception e){
                verif.setText("Statut : Erreur" + e.getMessage());
                
            }
            
        }
        
        
        
    }//GEN-LAST:event_chargeMouseClicked

    
    
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        listProd.removeAllItems();
        try{
                //on crée une connexion
                Connection con;

                //la voila on charge le driver
                Class.forName("org.gjt.mm.mysql.Driver");
                
                //on charge la connexion
                con = DriverManager.getConnection("jdbc:mysql://localhost/etudecas","root","root");
                
                //on cree ce qu'on doit faire sur l'objet que l'on doit faire.... tres philosophique je sais
                Statement statement = con.createStatement();
                
                //on execute une requete SELECT
                ResultSet resuProd = statement.executeQuery( "SELECT * FROM Producteur" );
                while(resuProd.next())
                    listProd.addItem(resuProd.getString(1) + " / " + resuProd.getString(2));
            }
            catch(Exception e){
                verif.setText("Statut : Erreur" + e.getMessage());
                
            }

    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Interface dialog = new Interface(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton charge;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> listProd;
    private javax.swing.JButton quit;
    private javax.swing.JLabel verif;
    // End of variables declaration//GEN-END:variables
}
